/// For contain error with message to display
class GeneralException implements Exception {
  final String? message;

  const GeneralException(this.message);
}
